In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('/home/konam/Downloads/budget_1920.xls')

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [3]:
df.describe()

,Sl. No.,2017-2018 - Actuals,2018-2019 - Budget Estimates,2018-2019 - Revised Estimates,2019-2020 - Budget Estimates
count,17.000000,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01
mean,9.000000,6.085340e+05,6.805568e+05,6.846113e+05,7.747349e+05
std,5.049752,7.221072e+05,8.367700e+05,8.400286e+05,9.572081e+05
min,1.000000,4.000000e-01,3.000000e-01,2.000000e-01,2.000000e-01
25%,5.000000,6.211200e+04,4.848100e+04,4.682800e+04,3.893800e+04
50%,9.000000,2.631400e+05,3.004410e+05,3.166230e+05,3.362930e+05
75%,13.000000,7.067420e+05,7.164750e+05,7.275530e+05,8.065070e+05
max,17.000000,2.141975e+06,2.442213e+06,2.457235e+06,2.784200e+06

In [4]:
df.columns

Index(['Sl. No.', 'Budget Receipts', '2017-2018 - Actuals',
       '2018-2019 - Budget Estimates', '2018-2019 - Revised Estimates',
       '2019-2020 - Budget Estimates'],
      dtype='object')

In [5]:
df.head()

,Sl. No.,Budget Receipts,2017-2018 - Actuals,2018-2019 - Budget Estimates,2018-2019 - Revised Estimates,2019-2020 - Budget Estimates
0,1.0,Revenue Receipts,1435233.0,1725738.0,1729682.0,1977693.0
1,2.0,Tax Revenue (Net to Centre),1242488.0,1480649.0,1484406.0,1705046.0
2,3.0,Non Tax Revenue,192745.0,245089.0,245276.0,272647.0
3,4.0,Capital Receipts1,706742.0,716475.0,727553.0,806507.0
4,5.0,Recovery of Loans,15633.0,12199.0,13155.0,12508.0

In [6]:
df.tail()

,Sl. No.,Budget Receipts,2017-2018 - Actuals,2018-2019 - Budget Estimates,2018-2019 - Revised Estimates,2019-2020 - Budget Estimates
16,NaN,Effective Revenue Deficit - Percentage of GDP,1.5,1.2,1.1,1.3
17,16.0,Fiscal Deficit [9-(1+5+6)],591064.0,624276.0,634398.0,703999.0
18,NaN,Fiscal Deficit - Percentage of GDP,3.5,3.3,3.4,3.4
19,17.0,Primary Deficit (16-11),62112.0,48481.0,46828.0,38938.0
20,NaN,Primary Deficit - Percentage of GDP,0.4,0.3,0.2,0.2

In [7]:
df

,Sl. No.,Budget Receipts,2017-2018 - Actuals,2018-2019 - Budget Estimates,2018-2019 - Revised Estimates,2019-2020 - Budget Estimates
0,1.0,Revenue Receipts,1435233.0,1725738.0,1729682.0,1977693.0
1,2.0,Tax Revenue (Net to Centre),1242488.0,1480649.0,1484406.0,1705046.0
2,3.0,Non Tax Revenue,192745.0,245089.0,245276.0,272647.0
3,4.0,Capital Receipts1,706742.0,716475.0,727553.0,806507.0
4,5.0,Recovery of Loans,15633.0,12199.0,13155.0,12508.0
5,6.0,Other Receipts,100045.0,80000.0,80000.0,90000.0
6,7.0,Borrowings and Other Liabilities2,591064.0,624276.0,634398.0,703999.0
7,8.0,Total Receipts (1+ 4),2141975.0,2442213.0,2457235.0,2784200.0
8,9.0,Total Expenditure (10+13),2141975.0,2442213.0,2457235.0,2784200.0
9,10.0,On Revenue Account of which,1878835.0,2141772.0,2140612.0,2447907.0
10,11.0,Interest Payments,528952.0,575795.0,587570.0,665061.0
11,12.0,Grants in Aid for creation of capital assests,191034.0,195345.0,200300.0,200740.0
12,13.0,On Capital Account,263140.0,300441.0,316623.0,336293.0
13,14.0,Revenue Deficit (10-1),443602.0,416034.0,410930.0,470214.0
14,NaN,Revenue Deficit - percentage of GDP,2.6,2.2,2.2,2.2
15,15.0,Effective Revenue Deficit (14-12),252568.0,220689.0,210630.0,269474.0
16,NaN,Effective Revenue Deficit - Percentage of GDP,1.5,1.2,1.1,1.3
17,16.0,Fiscal Deficit [9-(1+5+6)],591064.0,624276.0,634398.0,703999.0
18,NaN,Fiscal Deficit - Percentage of GDP,3.5,3.3,3.4,3.4
19,17.0,Primary Deficit (16-11),62112.0,48481.0,46828.0,38938.0
20,NaN,Primary Deficit - Percentage of GDP,0.4,0.3,0.2,0.2